version: 2
updates:
  - directory: /
    package-ecosystem: docker
    rebase-strategy: auto
    schedule:
      interval: daily
    ignore:
      - dependency-name: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
        versions:
          - ~>8.0-0 # ignores Elasticsearch 8 updates
